sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t deb538/docker-angular .

# script: This is used for unit testing
#   - docker run deb538/docker-angular

after_success:
  - docker build -t deb538/docker-angular .
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
  - docker push  deb538/docker-angular