sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t deb538/docker-angular -f dockerfile.dev .

script:
  - docker run deb538/docker-angular npm run test -- --coverage